### PR TITLE
Bump Why3 supported version (1.5 -> 1.6)

### LINKED ISSUE #350: EasyCrypt fails to build with Dune 3.7.0 + Merlin
EC builds normally after the standard sequences of `opam` commands, including

```
opam pin alt-ergo 2.4.2
```

Interestingly, before installing `alt-ergo` we were at 5.0.0, but after we downgrade to 4.14.1. `dune` is at 3.7.0.

After

```
opam install merlin
```

EasyCrypt no longer builds

```
File "src/ecUtils.ml", line 633, characters 22-36:
633 |     if s == aout then BatString.copy aout else s
                            ^^^^^^^^^^^^^^
Error: Unbound value BatString.copy
make: *** [build] Error 1 
```

and `opam list` shows (in particular the compiler is bumped back to
5.0.0):

```
alt-ergo              2.4.2       pinned to version 2.4.2
alt-ergo-lib          2.4.2       The Alt-Ergo SMT prover library
alt-ergo-parsers      2.4.2       The Alt-Ergo SMT prover parser library
base-bigarray         base
base-domains          base
base-nnp              base        Naked pointers prohibited in the OCaml heap
base-threads          base
base-unix             base
batteries             3.6.0       A community-maintained standard library extens
camlp-streams         5.0.1       The Stream and Genlex libraries for use with C
camlzip               1.11        Accessing compressed files in ZIP, GZIP and JA
cmdliner              1.1.1       Declarative definition of command line interfa
conf-autoconf         0.1         Virtual package relying on autoconf installati
conf-gmp              4           Virtual package relying on a GMP lib system in
conf-libpcre          1           Virtual package relying on a libpcre system in
conf-pkg-config       2           Check if pkg-config is installed and create an
conf-which            1           Virtual package relying on which
conf-zlib             1           Virtual package relying on zlib
cppo                  1.6.9       Code preprocessor like cpp for OCaml
csexp                 1.5.1       Parsing and printing of S-expressions in Canon
dot-merlin-reader     4.6         Reads config files for merlin
dune                  3.7.0       Fast, portable, and opinionated build system
dune-build-info       3.7.0       Embed build information inside executable
dune-configurator     3.7.0       Helper library for gathering system configurat
dune-private-libs     3.7.0       Private libraries of Dune
dune-site             3.7.0       Embed locations information inside executable 
dyn                   3.7.0       Dynamic type
menhir                20220210    An LR(1) parser generator
menhirLib             20220210    Runtime support library for parsers generated 
menhirSdk             20220210    Compile-time library for auxiliary tools relat
merlin                4.8-500     Editor helper, provides completion, typing and
merlin-lib            4.8-500     Merlin's libraries
num                   1.4         The legacy Num library for arbitrary-precision
ocaml                 5.0.0       The OCaml compiler (virtual package)
ocaml-base-compiler   5.0.0       Official release 5.0.0
ocaml-config          3           OCaml Switch Configuration
ocaml-inifiles        1.2         An ini file parser
ocaml-options-vanilla 1           Ensure that OCaml is compiled with no special 
ocamlbuild            0.14.2      OCamlbuild is a build system with builtin rule
ocamlfind             1.9.6       A library manager for OCaml
ocplib-simplex        0.4         A library implementing a simplex algorithm, in
ordering              3.7.0       Element ordering
pcre                  7.5.0       Bindings to the Perl Compatibility Regular Exp
pp                    1.1.2       Pretty-printing library
psmt2-frontend        0.4.0       The psmt2-frontend project
seq                   base        Compatibility package for OCaml's standard ite
stdlib-shims          0.3.0       Backport some of the new stdlib features to ol
stdune                3.7.0       Dune's unstable standard library
why3                  1.6.0       Why3 environment for deductive program verific
yojson                2.0.2       Yojson is an optimized parsing and printing li
zarith                1.12        Implements arithmetic and logical operations o
```

### PR DESCRIPTION
**Pull request by strub**
This makes EC compatible with OCaml 5.

Close #350

### CODE REVIEW

**Comment by strub** [comment]
@vbgl

**Comment by fdupress** [comment]
I'm going to change the default.nix to bake the Why3 version in. This will avoid synchronisation issues where we can't easily test version bumps until they actually cause problems, but requires keeping an eye on Why3 releases.

**Comment by fdupress** [comment]
@strub do you want the .nix change (fixing the why3 version to 1.5.1) in a separate PR that gets merged first? This PR would then updates the code and the build config for both opam and nix at the same time?

It does seem to compile locally.

**Comment by strub** [comment]
It seems that we are way slower. Please, refrain from merging this PR until we understand what is going on.

**Comment by fdupress** [comment]
And breaking jasmin's eclib—this wasn't checked in the previous run because nix-based compilation was failing.

**Comment by fdupress** [comment]
`StdBigop`, `Stdorder` and `Strong_RP_RF` account for most of the performance regression in the standard library.
`MEE-CBC/CBC` accounts for all the performance regression in the examples.

This is tested with ocaml 4.14.0 on both sides, with only the Why3 version (this PR) changing between the two runs.
Currently, my local run is showing 15 minutes spent on MEE-CBC/CBC, and progress stuck at 5.66%, so the issue is either in EC or in Why3. It does eventually get unstuck and completes.

I can't investigate this further today.

**Comment by fdupress** [comment]
It seems all hangups are on stray instances of raw `smt` calls (hidden in clone statements, so missed in earlier passes). These can be sorted out in the stdlib, but we should also track down why they hang for 30 minutes at a time.

Why3 1.6 API doc makes the time limit a float, which is "the maximum allowed running time in seconds". Why3 1.5.1 had it as an int, but also seems to indicate it specifies a number of seconds.

**Comment by fdupress** [comment]
Cancelling the workflows since the stdlib `smt` calls are not yet addressed, and I'd rather we spend our CI minutes on something that is not "waiting for smt calls to fail"

**Comment by strub** [comment]
@fdupress Are we set? IMO, we are.

**Comment by fdupress** [comment]
We've fixed the performance regression in the stlib, but not in general.
Are we happy to pass that cost to external proofs?

**Comment by strub** [comment]
IMO, we cannot avoid raw `smt` calls to have unstable behavior when the versions of Why3 / SMT solvers change.

**Comment by fdupress** [comment]
Then "Send it!"
